apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: app
  newName: gabriellls/ci-sum-2025
  newTag: latest
- name: hello-fastapi
  newName: gbrlls/fastapi-k8s
  newTag: 8410afbdc5ac499f7075a939fc18895ac035a5f9
